export default [
  { id: 1, src: "../img/3.png", color: "black", description: 1 },
  { id: 2, src: "../img/2.png", color: "green", description: 2 },
  { id: 3, src: "../img/1111111111.png", color: "yellow", description: 3 },
  { id: 4, src: "../img/зато.png", color: "grey", description: 4 },
  { id: 5, src: "../img/славік.png", color: "red", description: 5 },
  { id: 6, src: "../img/ккк.png", color: "gold", description: 6 },
  { id: 7, src: "../img/баг.png", color: "blue", description: 7 },
  { id: 8, src: "../img/4.png", color: "teal", description: 8 },
  {
    id: 9,
    src: "https://mdn.mozillademos.org/files/6457/mdn_logo_only_color.png",
    color: "orange",
    description: 9,
  },
  { id: 10, src: "../img/1.png", color: "aqua", description: 10 },
  { id: 11, src: "../img/.png", color: "purple", description: 11 },
  { id: 12, src: "../img/.png", color: "pink", description: 12 },
  { id: 13, src: "../img/.png", color: "brown", description: 13 },
  { id: 14, src: "../img/.png", color: "darkcyan", description: 14 },
  { id: 15, src: "../img/.png", color: "indigo", description: 15 },
  { id: 16, src: "../img/.png", color: "coral", description: 16 },
  { id: 17, src: "../img/.png", color: "navy", description: 17 },
  { id: 18, src: "../img/.png", color: "lime", description: 18 },
  { id: 19, src: "../img/.png", color: "olive", description: 19 },
  { id: 20, src: "../img/.png", color: "tan", description: 20 },
];
