export default [
  { id: 1, src: "", color: "black", description: 1 },
  { id: 2, src: "", color: "green", description: 2 },
  { id: 3, src: "", color: "yellow", description: 3 },
  { id: 4, src: "", color: "grey", description: 4 },
  { id: 5, src: "", color: "red", description: 5 },
  { id: 6, src: "", color: "gold", description: 6 },
  { id: 7, src: "", color: "blue", description: 7 },
  { id: 8, src: "", color: "teal", description: 8 },
  { id: 9, src: "", color: "orange", description: 9 },
  { id: 10, src: "", color: "aqua", description: 10 },
  { id: 11, src: "", color: "purple", description: 11 },
  { id: 12, src: "", color: "pink", description: 12 },
  { id: 13, src: "", color: "brown", description: 13 },
  { id: 14, src: "", color: "darkcyan", description: 14 },
  { id: 15, src: "", color: "indigo", description: 15 },
  { id: 16, src: "", color: "coral", description: 16 },
  { id: 17, src: "", color: "navy", description: 17 },
  { id: 18, src: "", color: "lime", description: 18 },
  { id: 19, src: "", color: "olive", description: 19 },
  { id: 20, src: "", color: "tan", description: 20 },
];
